### ISSUE TITLE
IndentationError when deployed to spaces

### ISSUE THREAD

**Issue by fcnjd** [TheStingerX/Ilaria-RVC-Mainline#66]
Hey,
thank you very much for all your work in this project, it is very much appreciated.
I believe that I found a bug, so would like to report it here: When removing the configs from the .gitignore (so that they also get deployed) and then running gradio deploy with app file infer-web.py, an IndentationError gets raised. The stacktrace is below. Is it really a bug, or just me doing things wrong?
Traceback (most recent call last):
  File "/home/user/app/infer-web.py", line 152, in <module>
    class ToolButton(gr.Button, gr.components.FormComponent):
  File "/home/user/.pyenv/versions/3.10.14/lib/python3.10/site-packages/gradio/component_meta.py", line 198, in __new__
    create_or_modify_pyi(component_class, name, events)
  File "/home/user/.pyenv/versions/3.10.14/lib/python3.10/site-packages/gradio/component_meta.py", line 117, in create_or_modify_pyi
    current_interface, _ = extract_class_source_code(pyi_file.read_text(), class_name)
  File "/home/user/.pyenv/versions/3.10.14/lib/python3.10/site-packages/gradio/component_meta.py", line 77, in extract_class_source_code
    class_ast = ast.parse(code)
  File "/home/user/.pyenv/versions/3.10.14/lib/python3.10/ast.py", line 50, in parse
    return compile(source, filename, mode, flags,
  File "<unknown>", line 153
    from gradio.events import Dependency
    ^^^^
IndentationError: expected an indented block after class definition on line 152

**Comment by TheStingerX** [comment]
are you trying to put it on HuggingFace?
