### ISSUE TITLE
Error when loading models

### ISSUE THREAD

**Issue by Dennoquellovero** [TheStingerX/Ilaria-RVC-Mainline#76]
I've come across some models that return an error when being loaded.
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/gradio/routes.py", line 437, in run_predict
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1346, in process_api
    result = await self.call_function(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1074, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/usr/local/lib/python3.10/dist-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/content/Ilaria-RVC-Mainline/infer/modules/vc/modules.py", line 108, in get_vc
    self.eps = self.cpt["info"]
KeyError: 'info'
```

The model is [https://huggingface.co/ScruffyRVC/RFCRVCV2/resolve/main/glados-p2.zip](https://huggingface.co/ScruffyRVC/RFCRVCV2/resolve/main/glados-p2.zip?download=true) by scruffygamer.

[https://huggingface.co/lyery/mymodels/resolve/main/GothEgirl.zip](https://huggingface.co/lyery/mymodels/resolve/main/GothEgirl.zip?download=true) by Lyery also suffers the same issue.

I don't know if this is known already, I'm reporting just in case.

**Comment by cappuch** [comment]
This error is directly tied to the models, testing on Mangio right now.
